//******************************************************************************************
// #Version 1.0#
//
// 		Includes: FBI Command Vehicle commands
//
//	- VcmdATFDeploy
//	- VcmdATFUnDeploy
//
//		Script by Hoppah
//		
//		Usage of this script in other mods is NOT allowed without permission of Hoppah
//
//******************************************************************************************

int DummyGroup = 28;

object VcmdATFDeploy : CommandScript
{
 	VcmdATFDeploy()
 	{
 		SetIcon("install");
 		SetCursor("install");
 		SetGroupID(DummyGroup);
 		SetGroupLeader(true);
 		SetRestrictions(RESTRICT_SELFEXECUTE);
		SetPriority(100);
 	}
 
 	bool CheckPossible(GameObject *Caller)
 	{
 		if (!Caller->IsValid())
 			return false;
 
 		if (Caller->GetType() == ACTOR_VEHICLE)
 		{
 			return true;
 		}
 
 		return false;
 	}
 
 	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
 	{
 		if (!Caller->IsValid() || !Target->IsValid() || Target->GetID() != Caller->GetID())
 			return false;
 
 		if (Caller->GetType() == ACTOR_VEHICLE)
 		{
 			return true;
 		}
 
 		return true;
 	}
 
	void PushActions(GameObject *Caller, Actor *Target, int childID)
 	{
 		Vehicle v(Caller);
		if (childID == 0)
		{
			v.PushActionWait(ACTION_NEWLIST, 4.0f);
			v.PushActionExecuteCommand(ACTION_APPEND, "VcmdATFDeploy", Caller, 1, false);
			v.SetCommandable(false);
			v.SetAnimation("Install");
			v.RemoveCommand("VcmdATFDeploy");
			v.AssignCommand("VcmdATFUnDeploy");
			v.RemoveCommand("MoveTo");
			v.RemoveCommand("GoHome");
		}
		if (childID == 1)
		{
			v.SetCommandable(true);
			v.EnableSpecialLights(true);
		}
	}
};

object VcmdATFUndeploy : CommandScript
{
 	VcmdATFUndeploy()
 	{
 		SetIcon("deinstall");
		SetCursor("deinstall");
 		SetGroupID(DummyGroup);
 		SetGroupLeader(true);
 		SetRestrictions(RESTRICT_SELFEXECUTE);
		SetPriority(100);
 	}
 
 	bool CheckPossible(GameObject *Caller)
 	{
 		if (!Caller->IsValid())
 			return false;
 
 		if (Caller->GetType() == ACTOR_VEHICLE)
 		{
 			return true;
 		}
 
 		return false;
 	}
 
 	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
 	{
 		if (!Caller->IsValid() || !Target->IsValid() || Target->GetID() != Caller->GetID())
 			return false;
 
 		if (Caller->GetType() == ACTOR_VEHICLE)
 		{
 			return true;
 		}
 
 		return true;
 	}
 
	void PushActions(GameObject *Caller, Actor *Target, int childID)
 	{
 		Vehicle v(Caller);
		if (childID == 0)
		{
			v.PushActionWait(ACTION_NEWLIST, 4.0f);
			v.PushActionExecuteCommand(ACTION_APPEND, "VcmdATFUndeploy", Caller, 1, false);
			v.EnableSpecialLights(false);
			v.SetCommandable(false);
			v.SetAnimation("Deinstall");
		}
		if (childID == 1)
		{
			v.AssignCommand("VcmdATFDeploy");
			v.RemoveCommand("VcmdATFUnDeploy");
			v.AssignCommand("MoveTo");
			v.AssignCommand("GoHome");
			v.SetCommandable(true);
		}
 	}	
};